language: csharp
sudo: required

# https://github.com/dotnet/docs/blob/master/.travis.yml

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      dotnet: 1.0.0-preview2-003121
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      dotnet: 1.0.0-preview2-003121

branches:
  only:
    - master

script:
  - dotnet --info
  - ./build.sh
