language: csharp
sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      dotnet: 1.0.0-preview2-003121
      mono: latest
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none

branches:
  only:
    - master

script:
  - dotnet --info
  - ./build.sh
