language: csharp
sudo: required
dotnet: 1.0.0-preview2-003121
mono: none # see comments in build.sh

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
    - os: osx # OSX 10.11
      osx_image: xcode7.2

branches:
  only:
    - master

before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh
